// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum CharacterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Character<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Character<'a> {
  type Inner = Character<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Character<'a> {
  pub const VT_WIDTH: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Character { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CharacterArgs<'args>
  ) -> flatbuffers::WIPOffset<Character<'bldr>> {
    let mut builder = CharacterBuilder::new(_fbb);
    if let Some(x) = args.width { builder.add_width(x); }
    builder.finish()
  }


  #[inline]
  pub fn width(&self) -> Option<&'a BitWidth> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<BitWidth>(Character::VT_WIDTH, None)}
  }
}

impl flatbuffers::Verifiable for Character<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<BitWidth>("width", Self::VT_WIDTH, false)?
     .finish();
    Ok(())
  }
}
pub struct CharacterArgs<'a> {
    pub width: Option<&'a BitWidth>,
}
impl<'a> Default for CharacterArgs<'a> {
  #[inline]
  fn default() -> Self {
    CharacterArgs {
      width: None,
    }
  }
}

pub struct CharacterBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CharacterBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_width(&mut self, width: &BitWidth) {
    self.fbb_.push_slot_always::<&BitWidth>(Character::VT_WIDTH, width);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CharacterBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CharacterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Character<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Character<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Character");
      ds.field("width", &self.width());
      ds.finish()
  }
}
