// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum FunctionMemberOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FunctionMember<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FunctionMember<'a> {
  type Inner = FunctionMember<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> FunctionMember<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: flatbuffers::VOffsetT = 6;
  pub const VT_LOCATION_TYPE: flatbuffers::VOffsetT = 8;
  pub const VT_LOCATION: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FunctionMember { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FunctionMemberArgs<'args>
  ) -> flatbuffers::WIPOffset<FunctionMember<'bldr>> {
    let mut builder = FunctionMemberBuilder::new(_fbb);
    if let Some(x) = args.location { builder.add_location(x); }
    if let Some(x) = args.type_ { builder.add_type_(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_location_type(args.location_type);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(FunctionMember::VT_NAME, None)}
  }
  #[inline]
  pub fn type_(&self) -> Type<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Type>>(FunctionMember::VT_TYPE_, None).unwrap()}
  }
  #[inline]
  pub fn location_type(&self) -> LocationClass {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<LocationClass>(FunctionMember::VT_LOCATION_TYPE, Some(LocationClass::NONE)).unwrap()}
  }
  #[inline]
  pub fn location(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(FunctionMember::VT_LOCATION, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn location_as_register_location(&self) -> Option<RegisterLocation<'a>> {
    if self.location_type() == LocationClass::RegisterLocation {
      self.location().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { RegisterLocation::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn location_as_stack_location(&self) -> Option<StackLocation<'a>> {
    if self.location_type() == LocationClass::StackLocation {
      self.location().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { StackLocation::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for FunctionMember<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Type>>("type_", Self::VT_TYPE_, true)?
     .visit_union::<LocationClass, _>("location_type", Self::VT_LOCATION_TYPE, "location", Self::VT_LOCATION, false, |key, v, pos| {
        match key {
          LocationClass::RegisterLocation => v.verify_union_variant::<flatbuffers::ForwardsUOffset<RegisterLocation>>("LocationClass::RegisterLocation", pos),
          LocationClass::StackLocation => v.verify_union_variant::<flatbuffers::ForwardsUOffset<StackLocation>>("LocationClass::StackLocation", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct FunctionMemberArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub type_: Option<flatbuffers::WIPOffset<Type<'a>>>,
    pub location_type: LocationClass,
    pub location: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for FunctionMemberArgs<'a> {
  #[inline]
  fn default() -> Self {
    FunctionMemberArgs {
      name: None,
      type_: None, // required field
      location_type: LocationClass::NONE,
      location: None,
    }
  }
}

pub struct FunctionMemberBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FunctionMemberBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FunctionMember::VT_NAME, name);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: flatbuffers::WIPOffset<Type<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Type>>(FunctionMember::VT_TYPE_, type_);
  }
  #[inline]
  pub fn add_location_type(&mut self, location_type: LocationClass) {
    self.fbb_.push_slot::<LocationClass>(FunctionMember::VT_LOCATION_TYPE, location_type, LocationClass::NONE);
  }
  #[inline]
  pub fn add_location(&mut self, location: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FunctionMember::VT_LOCATION, location);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FunctionMemberBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FunctionMemberBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FunctionMember<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FunctionMember::VT_TYPE_,"type_");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FunctionMember<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FunctionMember");
      ds.field("name", &self.name());
      ds.field("type_", &self.type_());
      ds.field("location_type", &self.location_type());
      match self.location_type() {
        LocationClass::RegisterLocation => {
          if let Some(x) = self.location_as_register_location() {
            ds.field("location", &x)
          } else {
            ds.field("location", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        LocationClass::StackLocation => {
          if let Some(x) = self.location_as_stack_location() {
            ds.field("location", &x)
          } else {
            ds.field("location", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("location", &x)
        },
      };
      ds.finish()
  }
}
