// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum FunctionMemberLocationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FunctionMemberLocation<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FunctionMemberLocation<'a> {
  type Inner = FunctionMemberLocation<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> FunctionMemberLocation<'a> {
  pub const VT_CLASS_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_CLASS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FunctionMemberLocation { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FunctionMemberLocationArgs
  ) -> flatbuffers::WIPOffset<FunctionMemberLocation<'bldr>> {
    let mut builder = FunctionMemberLocationBuilder::new(_fbb);
    if let Some(x) = args.class { builder.add_class(x); }
    builder.add_class_type(args.class_type);
    builder.finish()
  }


  #[inline]
  pub fn class_type(&self) -> LocationClass {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<LocationClass>(FunctionMemberLocation::VT_CLASS_TYPE, Some(LocationClass::NONE)).unwrap()}
  }
  #[inline]
  pub fn class(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(FunctionMemberLocation::VT_CLASS, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn class_as_register_location(&self) -> Option<RegisterLocation<'a>> {
    if self.class_type() == LocationClass::RegisterLocation {
      self.class().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { RegisterLocation::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn class_as_stack_location(&self) -> Option<StackLocation<'a>> {
    if self.class_type() == LocationClass::StackLocation {
      self.class().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { StackLocation::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for FunctionMemberLocation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<LocationClass, _>("class_type", Self::VT_CLASS_TYPE, "class", Self::VT_CLASS, false, |key, v, pos| {
        match key {
          LocationClass::RegisterLocation => v.verify_union_variant::<flatbuffers::ForwardsUOffset<RegisterLocation>>("LocationClass::RegisterLocation", pos),
          LocationClass::StackLocation => v.verify_union_variant::<flatbuffers::ForwardsUOffset<StackLocation>>("LocationClass::StackLocation", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct FunctionMemberLocationArgs {
    pub class_type: LocationClass,
    pub class: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for FunctionMemberLocationArgs {
  #[inline]
  fn default() -> Self {
    FunctionMemberLocationArgs {
      class_type: LocationClass::NONE,
      class: None,
    }
  }
}

pub struct FunctionMemberLocationBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FunctionMemberLocationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_class_type(&mut self, class_type: LocationClass) {
    self.fbb_.push_slot::<LocationClass>(FunctionMemberLocation::VT_CLASS_TYPE, class_type, LocationClass::NONE);
  }
  #[inline]
  pub fn add_class(&mut self, class: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FunctionMemberLocation::VT_CLASS, class);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FunctionMemberLocationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FunctionMemberLocationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FunctionMemberLocation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FunctionMemberLocation<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FunctionMemberLocation");
      ds.field("class_type", &self.class_type());
      match self.class_type() {
        LocationClass::RegisterLocation => {
          if let Some(x) = self.class_as_register_location() {
            ds.field("class", &x)
          } else {
            ds.field("class", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        LocationClass::StackLocation => {
          if let Some(x) = self.class_as_stack_location() {
            ds.field("class", &x)
          } else {
            ds.field("class", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("class", &x)
        },
      };
      ds.finish()
  }
}
