// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
#[allow(non_upper_case_globals)]
mod bitflags_structure_member_modifiers {
  flatbuffers::bitflags::bitflags! {
    #[derive(Default, Debug, Clone, Copy, PartialEq)]
    pub struct StructureMemberModifiers: u8 {
      const Internal = 1;
      const Flattened = 2;
    }
  }
}
pub use self::bitflags_structure_member_modifiers::StructureMemberModifiers;

impl<'a> flatbuffers::Follow<'a> for StructureMemberModifiers {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self::from_bits_retain(b)
  }
}

impl flatbuffers::Push for StructureMemberModifiers {
    type Output = StructureMemberModifiers;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.bits());
    }
}

impl flatbuffers::EndianScalar for StructureMemberModifiers {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.bits().to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self::from_bits_retain(b)
  }
}

impl<'a> flatbuffers::Verifiable for StructureMemberModifiers {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for StructureMemberModifiers {}
