// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum TypeChunkOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TypeChunk<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TypeChunk<'a> {
  type Inner = TypeChunk<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> TypeChunk<'a> {
  pub const VT_TYPES: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TypeChunk { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TypeChunkArgs<'args>
  ) -> flatbuffers::WIPOffset<TypeChunk<'bldr>> {
    let mut builder = TypeChunkBuilder::new(_fbb);
    if let Some(x) = args.types { builder.add_types(x); }
    builder.finish()
  }


  #[inline]
  pub fn types(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ComputedType<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ComputedType>>>>(TypeChunk::VT_TYPES, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for TypeChunk<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ComputedType>>>>("types", Self::VT_TYPES, true)?
     .finish();
    Ok(())
  }
}
pub struct TypeChunkArgs<'a> {
    pub types: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ComputedType<'a>>>>>,
}
impl<'a> Default for TypeChunkArgs<'a> {
  #[inline]
  fn default() -> Self {
    TypeChunkArgs {
      types: None, // required field
    }
  }
}

pub struct TypeChunkBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TypeChunkBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_types(&mut self, types: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ComputedType<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TypeChunk::VT_TYPES, types);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TypeChunkBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TypeChunkBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TypeChunk<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, TypeChunk::VT_TYPES,"types");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TypeChunk<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TypeChunk");
      ds.field("types", &self.types());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `TypeChunk`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_type_chunk_unchecked`.
pub fn root_as_type_chunk(buf: &[u8]) -> Result<TypeChunk, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<TypeChunk>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `TypeChunk` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_type_chunk_unchecked`.
pub fn size_prefixed_root_as_type_chunk(buf: &[u8]) -> Result<TypeChunk, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<TypeChunk>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `TypeChunk` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_type_chunk_unchecked`.
pub fn root_as_type_chunk_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TypeChunk<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<TypeChunk<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `TypeChunk` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_type_chunk_unchecked`.
pub fn size_prefixed_root_as_type_chunk_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TypeChunk<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<TypeChunk<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a TypeChunk and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `TypeChunk`.
pub unsafe fn root_as_type_chunk_unchecked(buf: &[u8]) -> TypeChunk {
  flatbuffers::root_unchecked::<TypeChunk>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed TypeChunk and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `TypeChunk`.
pub unsafe fn size_prefixed_root_as_type_chunk_unchecked(buf: &[u8]) -> TypeChunk {
  flatbuffers::size_prefixed_root_unchecked::<TypeChunk>(buf)
}
#[inline]
pub fn finish_type_chunk_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<TypeChunk<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_type_chunk_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<TypeChunk<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
