[workspace]
resolver = "2"
members = [
    "rust",
    "rust/fuzz",
    "warp_cli"
]

[workspace.dependencies]
warp = { path = "rust" }

[profile.release]
panic = "abort"
lto = true
debug = "full"

[profile.bench]
lto = true
