[package]
name = "warp_cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.83.0"

[dependencies]
warp = { workspace = true }
clap = { version = "4.5", features = ["derive"] }