// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum DataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Data<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Data<'a> {
  type Inner = Data<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Data<'a> {
  pub const VT_TYPES: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Data { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DataArgs<'args>
  ) -> flatbuffers::WIPOffset<Data<'bldr>> {
    let mut builder = DataBuilder::new(_fbb);
    if let Some(x) = args.types { builder.add_types(x); }
    builder.finish()
  }


  #[inline]
  pub fn types(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ComputedType<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ComputedType>>>>(Data::VT_TYPES, None)}
  }
}

impl flatbuffers::Verifiable for Data<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ComputedType>>>>("types", Self::VT_TYPES, false)?
     .finish();
    Ok(())
  }
}
pub struct DataArgs<'a> {
    pub types: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ComputedType<'a>>>>>,
}
impl<'a> Default for DataArgs<'a> {
  #[inline]
  fn default() -> Self {
    DataArgs {
      types: None,
    }
  }
}

pub struct DataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_types(&mut self, types: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ComputedType<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Data::VT_TYPES, types);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Data<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Data<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Data");
      ds.field("types", &self.types());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Data`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_data_unchecked`.
pub fn root_as_data(buf: &[u8]) -> Result<Data, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Data>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Data` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_data_unchecked`.
pub fn size_prefixed_root_as_data(buf: &[u8]) -> Result<Data, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Data>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Data` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_data_unchecked`.
pub fn root_as_data_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Data<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Data<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Data` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_data_unchecked`.
pub fn size_prefixed_root_as_data_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Data<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Data<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Data and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Data`.
pub unsafe fn root_as_data_unchecked(buf: &[u8]) -> Data {
  flatbuffers::root_unchecked::<Data>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Data and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Data`.
pub unsafe fn size_prefixed_root_as_data_unchecked(buf: &[u8]) -> Data {
  flatbuffers::size_prefixed_root_unchecked::<Data>(buf)
}
pub const DATA_IDENTIFIER: &str = "TBIN";

#[inline]
pub fn data_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, DATA_IDENTIFIER, false)
}

#[inline]
pub fn data_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, DATA_IDENTIFIER, true)
}

pub const DATA_EXTENSION: &str = "tbin";

#[inline]
pub fn finish_data_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Data<'a>>) {
  fbb.finish(root, Some(DATA_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_data_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Data<'a>>) {
  fbb.finish_size_prefixed(root, Some(DATA_IDENTIFIER));
}
