// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum DescriptorModifierClassOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DescriptorModifierClass<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DescriptorModifierClass<'a> {
  type Inner = DescriptorModifierClass<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DescriptorModifierClass<'a> {
  pub const VT_DESCRIPTION: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DescriptorModifierClass { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DescriptorModifierClassArgs<'args>
  ) -> flatbuffers::WIPOffset<DescriptorModifierClass<'bldr>> {
    let mut builder = DescriptorModifierClassBuilder::new(_fbb);
    if let Some(x) = args.description { builder.add_description(x); }
    builder.finish()
  }


  #[inline]
  pub fn description(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DescriptorModifierClass::VT_DESCRIPTION, None)}
  }
}

impl flatbuffers::Verifiable for DescriptorModifierClass<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("description", Self::VT_DESCRIPTION, false)?
     .finish();
    Ok(())
  }
}
pub struct DescriptorModifierClassArgs<'a> {
    pub description: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DescriptorModifierClassArgs<'a> {
  #[inline]
  fn default() -> Self {
    DescriptorModifierClassArgs {
      description: None,
    }
  }
}

pub struct DescriptorModifierClassBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DescriptorModifierClassBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_description(&mut self, description: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DescriptorModifierClass::VT_DESCRIPTION, description);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DescriptorModifierClassBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DescriptorModifierClassBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DescriptorModifierClass<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DescriptorModifierClass<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DescriptorModifierClass");
      ds.field("description", &self.description());
      ds.finish()
  }
}
