// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum EnumerationMemberOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EnumerationMember<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EnumerationMember<'a> {
  type Inner = EnumerationMember<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EnumerationMember<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_CONSTANT: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EnumerationMember { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EnumerationMemberArgs<'args>
  ) -> flatbuffers::WIPOffset<EnumerationMember<'bldr>> {
    let mut builder = EnumerationMemberBuilder::new(_fbb);
    builder.add_constant(args.constant);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(EnumerationMember::VT_NAME, None)}
  }
  #[inline]
  pub fn constant(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(EnumerationMember::VT_CONSTANT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for EnumerationMember<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<u64>("constant", Self::VT_CONSTANT, false)?
     .finish();
    Ok(())
  }
}
pub struct EnumerationMemberArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub constant: u64,
}
impl<'a> Default for EnumerationMemberArgs<'a> {
  #[inline]
  fn default() -> Self {
    EnumerationMemberArgs {
      name: None,
      constant: 0,
    }
  }
}

pub struct EnumerationMemberBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EnumerationMemberBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EnumerationMember::VT_NAME, name);
  }
  #[inline]
  pub fn add_constant(&mut self, constant: u64) {
    self.fbb_.push_slot::<u64>(EnumerationMember::VT_CONSTANT, constant, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EnumerationMemberBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EnumerationMemberBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EnumerationMember<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EnumerationMember<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EnumerationMember");
      ds.field("name", &self.name());
      ds.field("constant", &self.constant());
      ds.finish()
  }
}
