// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum StackLocationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StackLocation<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for StackLocation<'a> {
  type Inner = StackLocation<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> StackLocation<'a> {
  pub const VT_OFFSET: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    StackLocation { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StackLocationArgs<'args>
  ) -> flatbuffers::WIPOffset<StackLocation<'bldr>> {
    let mut builder = StackLocationBuilder::new(_fbb);
    if let Some(x) = args.offset { builder.add_offset(x); }
    builder.finish()
  }


  #[inline]
  pub fn offset(&self) -> &'a BitOffset {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<BitOffset>(StackLocation::VT_OFFSET, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for StackLocation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<BitOffset>("offset", Self::VT_OFFSET, true)?
     .finish();
    Ok(())
  }
}
pub struct StackLocationArgs<'a> {
    pub offset: Option<&'a BitOffset>,
}
impl<'a> Default for StackLocationArgs<'a> {
  #[inline]
  fn default() -> Self {
    StackLocationArgs {
      offset: None, // required field
    }
  }
}

pub struct StackLocationBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> StackLocationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_offset(&mut self, offset: &BitOffset) {
    self.fbb_.push_slot_always::<&BitOffset>(StackLocation::VT_OFFSET, offset);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> StackLocationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StackLocationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<StackLocation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, StackLocation::VT_OFFSET,"offset");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for StackLocation<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("StackLocation");
      ds.field("offset", &self.offset());
      ds.finish()
  }
}
