// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum SymbolOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Symbol<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Symbol<'a> {
  type Inner = Symbol<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Symbol<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_MODIFIERS: flatbuffers::VOffsetT = 6;
  pub const VT_CLASS: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Symbol { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SymbolArgs<'args>
  ) -> flatbuffers::WIPOffset<Symbol<'bldr>> {
    let mut builder = SymbolBuilder::new(_fbb);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_class(args.class);
    builder.add_modifiers(args.modifiers);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Symbol::VT_NAME, None)}
  }
  #[inline]
  pub fn modifiers(&self) -> SymbolModifiers {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<SymbolModifiers>(Symbol::VT_MODIFIERS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn class(&self) -> SymbolClass {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<SymbolClass>(Symbol::VT_CLASS, Some(SymbolClass::Function)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Symbol<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<SymbolModifiers>("modifiers", Self::VT_MODIFIERS, false)?
     .visit_field::<SymbolClass>("class", Self::VT_CLASS, false)?
     .finish();
    Ok(())
  }
}
pub struct SymbolArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub modifiers: SymbolModifiers,
    pub class: SymbolClass,
}
impl<'a> Default for SymbolArgs<'a> {
  #[inline]
  fn default() -> Self {
    SymbolArgs {
      name: None,
      modifiers: Default::default(),
      class: SymbolClass::Function,
    }
  }
}

pub struct SymbolBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SymbolBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Symbol::VT_NAME, name);
  }
  #[inline]
  pub fn add_modifiers(&mut self, modifiers: SymbolModifiers) {
    self.fbb_.push_slot::<SymbolModifiers>(Symbol::VT_MODIFIERS, modifiers, Default::default());
  }
  #[inline]
  pub fn add_class(&mut self, class: SymbolClass) {
    self.fbb_.push_slot::<SymbolClass>(Symbol::VT_CLASS, class, SymbolClass::Function);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SymbolBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SymbolBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Symbol<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Symbol<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Symbol");
      ds.field("name", &self.name());
      ds.field("modifiers", &self.modifiers());
      ds.field("class", &self.class());
      ds.finish()
  }
}
