[package]
name = "fbcg_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "24.3.25"

[build-dependencies]
flatbuffers-build = { git = "https://github.com/emesare/flatbuffers-build" }