// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod sig_bin {
  use super::*;
  mod basic_block_guid_generated;
  pub use self::basic_block_guid_generated::*;
  mod constraint_guid_generated;
  pub use self::constraint_guid_generated::*;
  mod function_guid_generated;
  pub use self::function_guid_generated::*;
  mod basic_block_generated;
  pub use self::basic_block_generated::*;
  mod constraint_generated;
  pub use self::constraint_generated::*;
  mod function_comment_generated;
  pub use self::function_comment_generated::*;
  mod function_variable_generated;
  pub use self::function_variable_generated::*;
  mod function_generated;
  pub use self::function_generated::*;
  mod signature_chunk_generated;
  pub use self::signature_chunk_generated::*;
} // sig_bin
pub mod symbol_bin {
  use super::*;
  mod symbol_class_generated;
  pub use self::symbol_class_generated::*;
  mod symbol_modifiers_generated;
  pub use self::symbol_modifiers_generated::*;
  mod symbol_generated;
  pub use self::symbol_generated::*;
} // symbol_bin
pub mod target_bin {
  use super::*;
  mod target_generated;
  pub use self::target_generated::*;
} // target_bin
pub mod type_bin {
  use super::*;
  mod type_modifiers_generated;
  pub use self::type_modifiers_generated::*;
  mod metadata_value_type_generated;
  pub use self::metadata_value_type_generated::*;
  mod pointer_addressing_generated;
  pub use self::pointer_addressing_generated::*;
  mod array_modifiers_generated;
  pub use self::array_modifiers_generated::*;
  mod structure_member_modifiers_generated;
  pub use self::structure_member_modifiers_generated::*;
  mod location_class_generated;
  pub use self::location_class_generated::*;
  mod type_class_generated;
  pub use self::type_class_generated::*;
  mod type_guid_generated;
  pub use self::type_guid_generated::*;
  mod unsigned_bit_offset_generated;
  pub use self::unsigned_bit_offset_generated::*;
  mod bit_offset_generated;
  pub use self::bit_offset_generated::*;
  mod bit_shift_generated;
  pub use self::bit_shift_generated::*;
  mod bit_size_generated;
  pub use self::bit_size_generated::*;
  mod bit_width_generated;
  pub use self::bit_width_generated::*;
  mod type_metadata_generated;
  pub use self::type_metadata_generated::*;
  mod void_generated;
  pub use self::void_generated::*;
  mod boolean_generated;
  pub use self::boolean_generated::*;
  mod float_generated;
  pub use self::float_generated::*;
  mod character_generated;
  pub use self::character_generated::*;
  mod integer_generated;
  pub use self::integer_generated::*;
  mod pointer_generated;
  pub use self::pointer_generated::*;
  mod array_generated;
  pub use self::array_generated::*;
  mod structure_member_generated;
  pub use self::structure_member_generated::*;
  mod structure_generated;
  pub use self::structure_generated::*;
  mod enumeration_member_generated;
  pub use self::enumeration_member_generated::*;
  mod enumeration_generated;
  pub use self::enumeration_generated::*;
  mod union_member_generated;
  pub use self::union_member_generated::*;
  mod union_generated;
  pub use self::union_generated::*;
  mod calling_convention_generated;
  pub use self::calling_convention_generated::*;
  mod register_location_generated;
  pub use self::register_location_generated::*;
  mod stack_location_generated;
  pub use self::stack_location_generated::*;
  mod function_member_generated;
  pub use self::function_member_generated::*;
  mod function_generated;
  pub use self::function_generated::*;
  mod referrer_generated;
  pub use self::referrer_generated::*;
  mod type_generated;
  pub use self::type_generated::*;
  mod computed_type_generated;
  pub use self::computed_type_generated::*;
  mod type_chunk_generated;
  pub use self::type_chunk_generated::*;
} // type_bin
pub mod warp {
  use super::*;
  mod chunk_type_generated;
  pub use self::chunk_type_generated::*;
  mod compression_type_generated;
  pub use self::compression_type_generated::*;
  mod chunk_header_generated;
  pub use self::chunk_header_generated::*;
  mod chunk_generated;
  pub use self::chunk_generated::*;
  mod file_header_generated;
  pub use self::file_header_generated::*;
  mod file_generated;
  pub use self::file_generated::*;
} // warp
