// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum FileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct File<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for File<'a> {
  type Inner = File<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> File<'a> {
  pub const VT_HEADER: flatbuffers::VOffsetT = 4;
  pub const VT_CHUNKS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    File { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FileArgs<'args>
  ) -> flatbuffers::WIPOffset<File<'bldr>> {
    let mut builder = FileBuilder::new(_fbb);
    if let Some(x) = args.chunks { builder.add_chunks(x); }
    if let Some(x) = args.header { builder.add_header(x); }
    builder.finish()
  }


  #[inline]
  pub fn header(&self) -> FileHeader<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<FileHeader>>(File::VT_HEADER, None).unwrap()}
  }
  #[inline]
  pub fn chunks(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Chunk<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Chunk>>>>(File::VT_CHUNKS, None)}
  }
}

impl flatbuffers::Verifiable for File<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<FileHeader>>("header", Self::VT_HEADER, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Chunk>>>>("chunks", Self::VT_CHUNKS, false)?
     .finish();
    Ok(())
  }
}
pub struct FileArgs<'a> {
    pub header: Option<flatbuffers::WIPOffset<FileHeader<'a>>>,
    pub chunks: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Chunk<'a>>>>>,
}
impl<'a> Default for FileArgs<'a> {
  #[inline]
  fn default() -> Self {
    FileArgs {
      header: None, // required field
      chunks: None,
    }
  }
}

pub struct FileBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_header(&mut self, header: flatbuffers::WIPOffset<FileHeader<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<FileHeader>>(File::VT_HEADER, header);
  }
  #[inline]
  pub fn add_chunks(&mut self, chunks: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Chunk<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(File::VT_CHUNKS, chunks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<File<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, File::VT_HEADER,"header");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for File<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("File");
      ds.field("header", &self.header());
      ds.field("chunks", &self.chunks());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `File`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_file_unchecked`.
pub fn root_as_file(buf: &[u8]) -> Result<File, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<File>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `File` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_file_unchecked`.
pub fn size_prefixed_root_as_file(buf: &[u8]) -> Result<File, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<File>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `File` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_file_unchecked`.
pub fn root_as_file_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<File<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<File<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `File` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_file_unchecked`.
pub fn size_prefixed_root_as_file_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<File<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<File<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a File and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `File`.
pub unsafe fn root_as_file_unchecked(buf: &[u8]) -> File {
  flatbuffers::root_unchecked::<File>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed File and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `File`.
pub unsafe fn size_prefixed_root_as_file_unchecked(buf: &[u8]) -> File {
  flatbuffers::size_prefixed_root_unchecked::<File>(buf)
}
pub const FILE_IDENTIFIER: &str = "WARP";

#[inline]
pub fn file_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, FILE_IDENTIFIER, false)
}

#[inline]
pub fn file_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, FILE_IDENTIFIER, true)
}

pub const FILE_EXTENSION: &str = "warp";

#[inline]
pub fn finish_file_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<File<'a>>) {
  fbb.finish(root, Some(FILE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_file_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<File<'a>>) {
  fbb.finish_size_prefixed(root, Some(FILE_IDENTIFIER));
}
