// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum BasicBlockOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BasicBlock<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for BasicBlock<'a> {
  type Inner = BasicBlock<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> BasicBlock<'a> {
  pub const VT_GUID: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    BasicBlock { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BasicBlockArgs<'args>
  ) -> flatbuffers::WIPOffset<BasicBlock<'bldr>> {
    let mut builder = BasicBlockBuilder::new(_fbb);
    if let Some(x) = args.guid { builder.add_guid(x); }
    builder.finish()
  }


  #[inline]
  pub fn guid(&self) -> &'a BasicBlockGUID {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<BasicBlockGUID>(BasicBlock::VT_GUID, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for BasicBlock<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<BasicBlockGUID>("guid", Self::VT_GUID, true)?
     .finish();
    Ok(())
  }
}
pub struct BasicBlockArgs<'a> {
    pub guid: Option<&'a BasicBlockGUID>,
}
impl<'a> Default for BasicBlockArgs<'a> {
  #[inline]
  fn default() -> Self {
    BasicBlockArgs {
      guid: None, // required field
    }
  }
}

pub struct BasicBlockBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> BasicBlockBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_guid(&mut self, guid: &BasicBlockGUID) {
    self.fbb_.push_slot_always::<&BasicBlockGUID>(BasicBlock::VT_GUID, guid);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> BasicBlockBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BasicBlockBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<BasicBlock<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, BasicBlock::VT_GUID,"guid");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for BasicBlock<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("BasicBlock");
      ds.field("guid", &self.guid());
      ds.finish()
  }
}
