// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
// struct FunctionGUID, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct FunctionGUID(pub [u8; 16]);
impl Default for FunctionGUID { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for FunctionGUID {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("FunctionGUID")
      .field("value", &self.value())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for FunctionGUID {}
impl<'a> flatbuffers::Follow<'a> for FunctionGUID {
  type Inner = &'a FunctionGUID;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a FunctionGUID>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a FunctionGUID {
  type Inner = &'a FunctionGUID;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<FunctionGUID>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for FunctionGUID {
    type Output = FunctionGUID;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const FunctionGUID as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(1)
    }
}

impl<'a> flatbuffers::Verifiable for FunctionGUID {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> FunctionGUID {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    value: &[u8; 16],
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_value(value);
    s
  }

  pub fn value(&'a self) -> flatbuffers::Array<'a, u8, 16> {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::Array::follow(&self.0, 0) }
  }

  pub fn set_value(&mut self, items: &[u8; 16]) {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::emplace_scalar_array(&mut self.0, 0, items) };
  }

}

